[package]
name = "akashic"
version = "0.1.1"
authors = ["SaltyAom <aomkirby123@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
actix-web = { version = "4.0.0-beta.20" }
actix-cors = "0.6.0-beta.8"
actix-files = "0.6.0-beta.14"

async-graphql = { version = "3.0.21", features = ["apollo_tracing"] }
async-graphql-actix-web = "3.0.21"

serde = "1.0.133"
serde_json = "1.0.75"
serde-aux = "3.0.1"

reqwest = { version = "0.11.9", default-features = false, features = ["rustls-tls"] }
cached = "0.29.0"
anyhow = "1.0.52"

tokio = { version = "1.15.0" }
futures = "0.3.19"
