[package]
name = "akashic"
version = "0.1.1"
authors = ["SaltyAom <aomkirby123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
actix-web = { version = "4.0.0-beta.9", default-features = false }
actix-cors = "0.6.0-beta.2"
actix-files = "0.6.0-beta.7"

async-graphql = { git = "https://github.com/async-graphql/async-graphql", branch = "actix-web-v4-beta", features = ["apollo_tracing"] }
async-graphql-actix-web = { git = "https://github.com/async-graphql/async-graphql", branch = "actix-web-v4-beta" }

serde = "1.0.130"
serde_json = "1.0.68"
serde-aux = "2.3.0"

reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls"] }
cached = "0.25.0"
chrono = "0.4.19"
anyhow = "1.0.44"
