[package]
name = "akashic"
version = "0.1.1"
authors = ["SaltyAom <aomkirby123@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
actix-web = { version = "4.0.0-beta.14" }
actix-cors = "0.6.0-beta.7"
actix-files = "0.6.0-beta.10"

async-graphql = { version = "3.0.17", features = ["apollo_tracing"] }
async-graphql-actix-web = "3.0.17"

serde = "1.0.130"
serde_json = "1.0.68"
serde-aux = "3.0.1"

reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls"] }
cached = "0.26.2"
anyhow = "1.0.44"
